,python_user,ubuntu1604,22.05.2017 01:53,file:///home/python_user/.config/libreoffice/4;